extends Node


const COLOR_DEFAULT = 100
const COLOR_RED = 101
const COLOR_YELLOW = 102
const COLOR_BLUE = 103
const COLOR_GREEN = 104

const COLORS = [COLOR_DEFAULT, COLOR_RED, COLOR_YELLOW, COLOR_BLUE, COLOR_GREEN]
